config/routes.rb
Rails.application.routes.draw do
  root "fortunes#index"

  resources :fortunes, only: [:create]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  FORTUNE_LIST = {
    error_rate: [
      "０％！カンペキの予感…！",
      "低め！スムーズに進むね！",
      "普通！落ち着いて調査しよう！",
      "高め…！無理せず、息抜きも大事かも…",
      "爆発寸前！？！？一旦PCの電源落としましょうか！？！？"
    ],
    bug_fortune: [
      "大吉！バグが起きない素敵な１日！", 
      "中吉！スラスラ書けるかも！",
      "小吉！今までの知識を思い出せば乗り越えられる…！", 
      "凶…！独り言をつぶやきながらバグと戦いましょう…", 
      "バグ地獄！…気分転換したほうが良いかも？"
    ],
    commit_power: [
      "爆上がり！！草超えて草原超えて森が生まれる…！！",  
      "絶好調！どんどんcommitできる！",
      "まあまあ！たくさん草を生やせそう！",
      "微妙…。１つでもcommit出来たら上出来！",
      "枯れ枯れ…。明日はcommitできるはず…！"
    ]
  }.freeze
  
  def index
  end

  def create
    @fortune = {
      error_rate:   FORTUNE_LIST[:error_rate].sample,
      bug_fortune:  FORTUNE_LIST[:bug_fortune].sample,
      commit_power: FORTUNE_LIST[:commit_power].sample
    }
    logger.debug(@fortune.inspect)
    render template: 'fortunes/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'エンジニアみくじ',
      title: 'エンジニアみくじ',
      reverse: true,
      charset: 'utf-8',
      description: 'あなたの今日のエンジニア運を占います',
      keywords: 'エンジニア,おみくじ,くじ,診断メーカー',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('icon.png') },
        { href: image_url('icon.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' },
      ],
      og:{
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'),
        local: 'ja-JP'
      },
      twitter: {
        card: 'summary_large_image',
        site: '@satoeri_63b',
        image: image_url('ogp.png')
      }
    }
  end
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/views/fortunes/_fortune.html.erb
<% if fortune.present? %>
  <turbo-frame id="fortune_result">
    <div class="card shadow-sm mt-4" style="margin: auto; width: 70%;">
      <div class="card-body text-center">
        <h2 class="mb-3">🎲 今日のエンジニア運勢 🎲</h2>
        <p class="animate__animated animate__bounceInDown" style="animation-delay: 0s;">
          <strong>エラー率:</strong> <span class="text-danger"><%= fortune[:error_rate] %></span>
        </p>
        <p class="animate__animated animate__bounceInDown" style="animation-delay: 0.3s;">
          <strong>バグ運:</strong> <span class="text-primary"><%= fortune[:bug_fortune] %></span>
        </p>
        <p class="animate__animated animate__bounceInDown" style="animation-delay: 0.6s;">
          <strong>コミットパワー:</strong> <span class="text-success"><%= fortune[:commit_power] %></span>
        </p>

        <!-- Twitterシェア -->
        <%= link_to "https://twitter.com/intent/tweet?text=
【エンジニアみくじの結果】%0a
  エラー率 : #{@fortune[:error_rate]}%0a
  バグ運 : #{@fortune[:bug_fortune]}%0a
  コミットパワー : #{@fortune[:commit_power]}%0a%0a
  %23エンジニアみくじ%0a
  &url=#{request.base_url}", class: "btn btn-info btn-lg mt-3", target: "_blank" do %>
          <i class="fab fa-twitter mr-1" style='color: #FFFFFF;'></i>Twitterでシェア
        <% end %>
      </div>
    </div>
  </turbo-frame>
<% end %>

app/views/fortunes/index.html.erb
<h1>エンジニアみくじ</h1>

<%= button_to "今日の運勢を占う！", fortunes_path, method: :post, form: {data: {turbo_frame: "fortune_result"}}, class: "btn btn-primary" %>

<%= turbo_frame_tag "fortune_result" do %>
  <% if @fortune %>
    <%= render partial: "fortune", locals: { fortune: @fortune } %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "エンジニアみくじ" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+HarunoUmi&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= display_meta_tags(default_meta_tags) %>
  </head>

  <body class="text-center" style="background:#F6DFEC; font-family: 'Kaisei HarunoUmi', serif; margin-top: 5%;">
    <%= yield %>
  </body>
</html>